services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  fmdd.manager.promotion_manager:
    class: FMDD\SyliusPromotionPlugin\Manager\PromotionManager

  FMDD\SyliusPromotionPlugin\Manager\PromotionManager: '@fmdd.manager.promotion_manager'

  sylius.promotion_action.unit_percentage_discount_threshold:
    class: FMDD\SyliusPromotionPlugin\Promotion\Action\UnitPercentageDiscountThresholdPromotionActionCommand
    arguments:
      - '@sylius.factory.adjustment'
      - '@sylius.promotion_filter.product'
      - '@sylius.promotion_filter.taxon'
      - '@sylius.promotion_filter.price_range'
    tags:
      - { name: sylius.promotion_action, type: unit_percentage_discount_threshold, label: fmdd.item_percentage_discount_threshold.label, form_type: FMDD\SyliusPromotionPlugin\Form\Type\ChannelBasedUnitPercentageDiscountThresholdConfigurationType }

  sylius.promotion_action.free_threshold:
    class: FMDD\SyliusPromotionPlugin\Promotion\Action\FreeThresholdPromotionActionCommand
    arguments:
      $adjustmentFactory: '@sylius.factory.adjustment'
      $productFilter: '@sylius.promotion_filter.product'
      $productRepository: '@sylius.repository.product'
      $orderItemFactory: '@sylius.factory.order_item'
      $itemQuantityModifier: '@sylius.order_item_quantity_modifier'
      $taxonFilter: '@sylius.promotion_filter.taxon'
      $priceRangeFilter: '@sylius.promotion_filter.price_range'
    tags:
      - { name: sylius.promotion_action, type: free_threshold, label: fmdd.free_threshold.label, form_type: FMDD\SyliusPromotionPlugin\Form\Type\ChannelBasedFreeThresholdConfigurationType }

  FMDD\SyliusPromotionPlugin\Form\Type\UnitPercentageDiscountThresholdConfigurationType:
    arguments:
      - '@sylius.repository.product'
    tags:
      - { name: form.type }

  FMDD\SyliusPromotionPlugin\Form\Type\FreeThresholdConfigurationType:
    arguments:
      - '@sylius.repository.product'
    tags:
      - { name: form.type }
